name: Staging deployment

on:
  pull_request:
    types: [labeled]
    
env:
  DOCKER_IMAGE_NAME: simonthurman-azure-ttt
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  
  AZURE_WEBAPP_NAME: simonthurman-ttt-app
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    if: contains(github.event.pull_request.labels.*.name, 'stage')
